CREATE TABLE seat_maps (
    id UUID PRIMARY KEY,
    aircraft VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cabins (
    id UUID PRIMARY KEY,
    seat_map_id UUID NOT NULL,
    deck VARCHAR(50) NOT NULL,
    seat_columns VARCHAR(50)[] NOT NULL,
    first_row INT NOT NULL,
    last_row INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (seat_map_id) REFERENCES seat_maps (id) ON DELETE CASCADE
);

CREATE TABLE seat_rows (
    id UUID PRIMARY KEY,
    cabin_id UUID NOT NULL,
    row_number INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cabin_id) REFERENCES cabins (id) ON DELETE CASCADE
);

CREATE TABLE seats (
    id UUID PRIMARY KEY,
    seat_row_id UUID NOT NULL,
    storefront_slot_code VARCHAR(50) NOT NULL,
    available BOOLEAN NOT NULL,
    code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (seat_row_id) REFERENCES seat_rows (id) ON DELETE CASCADE
)
